version: '3.8'

services:
  go:
   image: golang:1.23
   container_name: go
   working_dir: /go/src/app
   tty: true
   depends_on:
     - db
   ports:
     - "3000:3000"
   volumes:
      - ./src:/go/src/app

  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64 # for M1 Mac
    container_name: phpMyAdmin
    depends_on:
      - db
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: pass
    ports:
      - "4000:80"
      
  db:
    image: mysql:8.0
    container_name: mysql
    platform: linux/amd64 # for M1 Mac
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: game
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    ports: 
    - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
    

    

# phpMyAdmin localhost:4000
# swagger localhost:3000