version: '3.8'

services:
  go:
   image: golang:1.23
   container_name: go
   working_dir: /go/src/app
   tty: true
   depends_on:
     - mysql
   volumes:
      - ./src:/go/src/app
   ports:
     - "8000:8000"
      
  mysql:
    image: mysql:8.0
    container_name: mysql
    platform: linux/amd64 # for M1 Mac
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: 42tokyo-road-to-dojo-go_db-data
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    ports: 
    - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  phpmyAdmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64 # for M1 Mac
    container_name: phpmyAdmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: pass
    ports:
      - "4000:80"
  
  radis:
    image: redis:7.4
    container_name: radis
    platform: linux/amd64 # for M1 Mac
    ports:
      - "6379:6379"
    # NOTE: volumesを追加するかも

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    environment:
      SWAGGER_JSON: /openapi.yml
    ports:
      - "3000:8080"
    volumes:
      - ./api/openapi.yml:/openapi.yml

volumes:
  mysql_data:
    driver: local


    

# phpMyAdmin localhost:4000
# swagger localhost:3000